# Generated by Django 4.0.6 on 2022-07-26 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_goods', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('local', models.CharField(max_length=120)),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='goods.merchandise')),
            ],
        ),
    ]
