# Generated by Django 4.0.6 on 2022-07-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_input_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='created_at',
        ),
    ]
