# Generated by Django 4.0.6 on 2022-07-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_merchandise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='type',
            field=models.CharField(max_length=120),
        ),
    ]
