# Generated by Django 4.0.6 on 2022-07-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_merchandise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
