# Generated by Django 4.0.6 on 2022-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_merchandise_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
