# Generated by Django 4.0.6 on 2022-07-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0003_remove_output_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='type',
            field=models.CharField(default='output', max_length=120),
        ),
    ]
